### ISSUE TITLE
Show Header User dropdown only if the user is logged in

### ISSUE THREAD

**Issue by kevinmamaqi** [IT-Academy-BCN/ita-directory#580]

**Comment by adaldin** [comment]
Issue closed since dropdown is working now.
Screenshots:

Header.jsx renders UserAccess.jsx that manage state and get isLoggedIn state:
1-header-renders-userAccess
2)In UserAccess.jsx, redux hook(useSelector), get the user isLoggedIn status(true-false):
2-userAccess-renders-dropdown-if-logged-in

3)UserAccess.jsx return a btn element is user isLoggedIn + the component Dropdown.jsx with the list of routes. If user is not logged (!isLoggedIn), returns "Registrarme" btn:
3-userAccess-returns-dropdown

4)Demo of issue solved on web:
4-demo-dropdown-only-when-logged-ond
